/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by vite-plugin-uni-pages

interface NavigateToOptions {
  url: "/pages/index/index" |
       "/pages/about/about" |
       "/pages/demo1/index" |
       "/pages/demo2/index" |
       "/pages/demo3/index" |
       "/pages/finance/finance" |
       "/pages/finance/index" |
       "/pages/finance-center/finance-center" |
       "/pages/home/index" |
       "/pages/login/index" |
       "/pages/login/login" |
       "/pages/mine/mine" |
       "/pages/other-login/other-login" |
       "/pages/policy/policy";
}
interface RedirectToOptions extends NavigateToOptions {}

interface SwitchTabOptions {
  url: "/pages/index/index" | "/pages/finance-center/finance-center" | "/pages/policy/policy" | "/pages/mine/mine"
}

type ReLaunchOptions = NavigateToOptions | SwitchTabOptions;

declare interface Uni {
  navigateTo(options: UniNamespace.NavigateToOptions & NavigateToOptions): void;
  redirectTo(options: UniNamespace.RedirectToOptions & RedirectToOptions): void;
  switchTab(options: UniNamespace.SwitchTabOptions & SwitchTabOptions): void;
  reLaunch(options: UniNamespace.ReLaunchOptions & ReLaunchOptions): void;
}
