/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by vite-plugin-uni-pages

interface NavigateToOptions {
  url: "/pages/index/index" |
       "/pages/finance/finance" |
       "/pages/finance-center/finance-center" |
       "/pages/login/login" |
       "/pages/mine/mine" |
       "/pages/other-login/other-login" |
       "/pages/policy/policy" |
       "/pages-sub/assetDataTable/assetDataTable" |
       "/pages-sub/enterpriseVerify/enterpriseVerify" |
       "/pages-sub/faceAuthentication/faceAuthentication" |
       "/pages-sub/policyDetails/policyDetails" |
       "/pages-sub/productApplication/productApplication" |
       "/pages-sub/productDetail/productDetail" |
       "/pages-sub/requirementList/requirementList" |
       "/pages-sub/search/search" |
       "/pages-sub/searchInput/searchInput" |
       "/pages-sub/setting/setting" |
       "/pages-sub/smartMatching/smartMatching" |
       "/pages-sub/supplyTrade/supplyTrade" |
       "/pages-sub/userVerify/userVerify";
}
interface RedirectToOptions extends NavigateToOptions {}

interface SwitchTabOptions {
  url: "/pages/index/index" | "/pages/finance-center/finance-center" | "/pages/policy/policy" | "/pages/mine/mine"
}

type ReLaunchOptions = NavigateToOptions | SwitchTabOptions;

declare interface Uni {
  navigateTo(options: UniNamespace.NavigateToOptions & NavigateToOptions): void;
  redirectTo(options: UniNamespace.RedirectToOptions & RedirectToOptions): void;
  switchTab(options: UniNamespace.SwitchTabOptions & SwitchTabOptions): void;
  reLaunch(options: UniNamespace.ReLaunchOptions & ReLaunchOptions): void;
}
